version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Nothing to install
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: dist
  files:
    - '**/*'
