version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Nothing to install
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 rm --recursive "s3://${ARTIFACTS_BUCKET}/"
artifacts:
  base-directory: dist
  files:
    - '**/*'
